
a.out: main.c ../../src/tpp.h ../../src/tpp.c mywrapper-for-tpp.h mywrapper-for-tpp.c my-custom-tpp-defs.h
	gcc -o a.out main.c mywrapper-for-tpp.c

a.exe: main.c ../../src/tpp.h ../../src/tpp.c mywrapper-for-tpp.h mywrapper-for-tpp.c my-custom-tpp-defs.h
	gcc -o a.exe main.c mywrapper-for-tpp.c
